// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

pub type ControllerEventMask = u32;
pub type DeviceEventMask = u32;
pub type KeyEventMask = u32;
pub type KeyMaskType = u32;
pub type KeystrokeListener = /*Unimplemented*/();
