// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "AtspiDocument")]
    pub struct Document(Interface<ffi::AtspiDocument>);

    match fn {
        type_ => || ffi::atspi_document_get_type(),
    }
}

pub const NONE_DOCUMENT: Option<&Document> = None;

pub trait DocumentExt: 'static {
    #[cfg_attr(feature = "v2_10", deprecated = "Since 2.10")]
    #[doc(alias = "atspi_document_get_attribute_value")]
    #[doc(alias = "get_attribute_value")]
    fn attribute_value(&self, attribute: &str) -> Result<glib::GString, glib::Error>;

    //#[cfg_attr(feature = "v2_10", deprecated = "Since 2.10")]
    //#[doc(alias = "atspi_document_get_attributes")]
    //#[doc(alias = "get_attributes")]
    //fn attributes(&self) -> Result</*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }, glib::Error>;

    #[doc(alias = "atspi_document_get_current_page_number")]
    #[doc(alias = "get_current_page_number")]
    fn current_page_number(&self) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_document_get_document_attribute_value")]
    #[doc(alias = "get_document_attribute_value")]
    fn document_attribute_value(&self, attribute: &str) -> Result<glib::GString, glib::Error>;

    //#[doc(alias = "atspi_document_get_document_attributes")]
    //#[doc(alias = "get_document_attributes")]
    //fn document_attributes(&self) -> Result</*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }, glib::Error>;

    #[doc(alias = "atspi_document_get_locale")]
    #[doc(alias = "get_locale")]
    fn locale(&self) -> Result<glib::GString, glib::Error>;

    #[doc(alias = "atspi_document_get_page_count")]
    #[doc(alias = "get_page_count")]
    fn page_count(&self) -> Result<i32, glib::Error>;
}

impl<O: IsA<Document>> DocumentExt for O {
    fn attribute_value(&self, attribute: &str) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_document_get_attribute_value(self.as_ref().to_glib_none().0, attribute.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //fn attributes(&self) -> Result</*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }, glib::Error> {
    //    unsafe { TODO: call ffi:atspi_document_get_attributes() }
    //}

    fn current_page_number(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_document_get_current_page_number(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn document_attribute_value(&self, attribute: &str) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_document_get_document_attribute_value(self.as_ref().to_glib_none().0, attribute.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //fn document_attributes(&self) -> Result</*Unknown conversion*//*Unimplemented*/HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }, glib::Error> {
    //    unsafe { TODO: call ffi:atspi_document_get_document_attributes() }
    //}

    fn locale(&self) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_document_get_locale(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn page_count(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_document_get_page_count(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }
}

impl fmt::Display for Document {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Document")
    }
}
