// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Event(Boxed<ffi::AtspiEvent>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::atspi_event_get_type(), ptr as *mut _) as *mut ffi::AtspiEvent,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::atspi_event_get_type(), ptr as *mut _),
        type_ => || ffi::atspi_event_get_type(),
    }
}

impl Event {
    #[doc(alias = "atspi_event_main")]
    pub fn main() {
        unsafe {
            ffi::atspi_event_main();
        }
    }

    #[doc(alias = "atspi_event_quit")]
    pub fn quit() {
        unsafe {
            ffi::atspi_event_quit();
        }
    }
}
