// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use crate::Accessible;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::mem;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "AtspiTable")]
    pub struct Table(Interface<ffi::AtspiTable>);

    match fn {
        type_ => || ffi::atspi_table_get_type(),
    }
}

pub const NONE_TABLE: Option<&Table> = None;

pub trait TableExt: 'static {
    #[doc(alias = "atspi_table_add_column_selection")]
    fn add_column_selection(&self, column: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_add_row_selection")]
    fn add_row_selection(&self, row: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_get_accessible_at")]
    #[doc(alias = "get_accessible_at")]
    fn accessible_at(&self, row: i32, column: i32) -> Result<Accessible, glib::Error>;

    #[doc(alias = "atspi_table_get_caption")]
    #[doc(alias = "get_caption")]
    fn caption(&self) -> Result<Accessible, glib::Error>;

    #[doc(alias = "atspi_table_get_column_at_index")]
    #[doc(alias = "get_column_at_index")]
    fn column_at_index(&self, index: i32) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_column_description")]
    #[doc(alias = "get_column_description")]
    fn column_description(&self, column: i32) -> Result<glib::GString, glib::Error>;

    #[doc(alias = "atspi_table_get_column_extent_at")]
    #[doc(alias = "get_column_extent_at")]
    fn column_extent_at(&self, row: i32, column: i32) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_column_header")]
    #[doc(alias = "get_column_header")]
    fn column_header(&self, column: i32) -> Result<Accessible, glib::Error>;

    #[doc(alias = "atspi_table_get_index_at")]
    #[doc(alias = "get_index_at")]
    fn index_at(&self, row: i32, column: i32) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_n_columns")]
    #[doc(alias = "get_n_columns")]
    fn n_columns(&self) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_n_rows")]
    #[doc(alias = "get_n_rows")]
    fn n_rows(&self) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_n_selected_columns")]
    #[doc(alias = "get_n_selected_columns")]
    fn n_selected_columns(&self) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_n_selected_rows")]
    #[doc(alias = "get_n_selected_rows")]
    fn n_selected_rows(&self) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_row_at_index")]
    #[doc(alias = "get_row_at_index")]
    fn row_at_index(&self, index: i32) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_row_column_extents_at_index")]
    #[doc(alias = "get_row_column_extents_at_index")]
    fn row_column_extents_at_index(&self, index: i32) -> Result<(i32, i32, i32, i32, bool), glib::Error>;

    #[doc(alias = "atspi_table_get_row_description")]
    #[doc(alias = "get_row_description")]
    fn row_description(&self, row: i32) -> Result<glib::GString, glib::Error>;

    #[doc(alias = "atspi_table_get_row_extent_at")]
    #[doc(alias = "get_row_extent_at")]
    fn row_extent_at(&self, row: i32, column: i32) -> Result<i32, glib::Error>;

    #[doc(alias = "atspi_table_get_row_header")]
    #[doc(alias = "get_row_header")]
    fn row_header(&self, row: i32) -> Result<Accessible, glib::Error>;

    //#[doc(alias = "atspi_table_get_selected_columns")]
    //#[doc(alias = "get_selected_columns")]
    //fn selected_columns(&self) -> Result</*Unknown conversion*//*Unimplemented*/Array TypeId { ns_id: 0, id: 14 }, glib::Error>;

    //#[doc(alias = "atspi_table_get_selected_rows")]
    //#[doc(alias = "get_selected_rows")]
    //fn selected_rows(&self) -> Result</*Unknown conversion*//*Unimplemented*/Array TypeId { ns_id: 0, id: 14 }, glib::Error>;

    #[doc(alias = "atspi_table_get_summary")]
    #[doc(alias = "get_summary")]
    fn summary(&self) -> Result<Accessible, glib::Error>;

    #[doc(alias = "atspi_table_is_column_selected")]
    fn is_column_selected(&self, column: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_is_row_selected")]
    fn is_row_selected(&self, row: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_is_selected")]
    fn is_selected(&self, row: i32, column: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_remove_column_selection")]
    fn remove_column_selection(&self, column: i32) -> Result<(), glib::Error>;

    #[doc(alias = "atspi_table_remove_row_selection")]
    fn remove_row_selection(&self, row: i32) -> Result<(), glib::Error>;
}

impl<O: IsA<Table>> TableExt for O {
    fn add_column_selection(&self, column: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_add_column_selection(self.as_ref().to_glib_none().0, column, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn add_row_selection(&self, row: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_add_row_selection(self.as_ref().to_glib_none().0, row, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn accessible_at(&self, row: i32, column: i32) -> Result<Accessible, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_accessible_at(self.as_ref().to_glib_none().0, row, column, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn caption(&self) -> Result<Accessible, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_caption(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn column_at_index(&self, index: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_column_at_index(self.as_ref().to_glib_none().0, index, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn column_description(&self, column: i32) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_column_description(self.as_ref().to_glib_none().0, column, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn column_extent_at(&self, row: i32, column: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_column_extent_at(self.as_ref().to_glib_none().0, row, column, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn column_header(&self, column: i32) -> Result<Accessible, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_column_header(self.as_ref().to_glib_none().0, column, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn index_at(&self, row: i32, column: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_index_at(self.as_ref().to_glib_none().0, row, column, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn n_columns(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_n_columns(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn n_rows(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_n_rows(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn n_selected_columns(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_n_selected_columns(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn n_selected_rows(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_n_selected_rows(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn row_at_index(&self, index: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_row_at_index(self.as_ref().to_glib_none().0, index, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn row_column_extents_at_index(&self, index: i32) -> Result<(i32, i32, i32, i32, bool), glib::Error> {
        unsafe {
            let mut row = mem::MaybeUninit::uninit();
            let mut col = mem::MaybeUninit::uninit();
            let mut row_extents = mem::MaybeUninit::uninit();
            let mut col_extents = mem::MaybeUninit::uninit();
            let mut is_selected = mem::MaybeUninit::uninit();
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_get_row_column_extents_at_index(self.as_ref().to_glib_none().0, index, row.as_mut_ptr(), col.as_mut_ptr(), row_extents.as_mut_ptr(), col_extents.as_mut_ptr(), is_selected.as_mut_ptr(), &mut error);
            let row = row.assume_init();
            let col = col.assume_init();
            let row_extents = row_extents.assume_init();
            let col_extents = col_extents.assume_init();
            let is_selected = is_selected.assume_init();
            if error.is_null() { Ok((row, col, row_extents, col_extents, from_glib(is_selected))) } else { Err(from_glib_full(error)) }
        }
    }

    fn row_description(&self, row: i32) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_row_description(self.as_ref().to_glib_none().0, row, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn row_extent_at(&self, row: i32, column: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_row_extent_at(self.as_ref().to_glib_none().0, row, column, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn row_header(&self, row: i32) -> Result<Accessible, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_row_header(self.as_ref().to_glib_none().0, row, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //fn selected_columns(&self) -> Result</*Unknown conversion*//*Unimplemented*/Array TypeId { ns_id: 0, id: 14 }, glib::Error> {
    //    unsafe { TODO: call ffi:atspi_table_get_selected_columns() }
    //}

    //fn selected_rows(&self) -> Result</*Unknown conversion*//*Unimplemented*/Array TypeId { ns_id: 0, id: 14 }, glib::Error> {
    //    unsafe { TODO: call ffi:atspi_table_get_selected_rows() }
    //}

    fn summary(&self) -> Result<Accessible, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::atspi_table_get_summary(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn is_column_selected(&self, column: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_is_column_selected(self.as_ref().to_glib_none().0, column, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn is_row_selected(&self, row: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_is_row_selected(self.as_ref().to_glib_none().0, row, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn is_selected(&self, row: i32, column: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_is_selected(self.as_ref().to_glib_none().0, row, column, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn remove_column_selection(&self, column: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_remove_column_selection(self.as_ref().to_glib_none().0, column, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn remove_row_selection(&self, row: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::atspi_table_remove_row_selection(self.as_ref().to_glib_none().0, row, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }
}

impl fmt::Display for Table {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Table")
    }
}
