// Generated by gir (https://github.com/gtk-rs/gir @ e8f82cf)
// from ../gir-files (@ 915ec7c)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AtspiAccessible", sizeof(AtspiAccessible), alignof(AtspiAccessible));
    printf("%s;%zu;%zu\n", "AtspiAccessibleClass", sizeof(AtspiAccessibleClass), alignof(AtspiAccessibleClass));
    printf("%s;%zu;%zu\n", "AtspiApplication", sizeof(AtspiApplication), alignof(AtspiApplication));
    printf("%s;%zu;%zu\n", "AtspiApplicationClass", sizeof(AtspiApplicationClass), alignof(AtspiApplicationClass));
    printf("%s;%zu;%zu\n", "AtspiCache", sizeof(AtspiCache), alignof(AtspiCache));
    printf("%s;%zu;%zu\n", "AtspiCollectionMatchType", sizeof(AtspiCollectionMatchType), alignof(AtspiCollectionMatchType));
    printf("%s;%zu;%zu\n", "AtspiCollectionSortOrder", sizeof(AtspiCollectionSortOrder), alignof(AtspiCollectionSortOrder));
    printf("%s;%zu;%zu\n", "AtspiCollectionTreeTraversalType", sizeof(AtspiCollectionTreeTraversalType), alignof(AtspiCollectionTreeTraversalType));
    printf("%s;%zu;%zu\n", "AtspiComponentLayer", sizeof(AtspiComponentLayer), alignof(AtspiComponentLayer));
    printf("%s;%zu;%zu\n", "AtspiControllerEventMask", sizeof(AtspiControllerEventMask), alignof(AtspiControllerEventMask));
    printf("%s;%zu;%zu\n", "AtspiCoordType", sizeof(AtspiCoordType), alignof(AtspiCoordType));
    printf("%s;%zu;%zu\n", "AtspiDeviceEvent", sizeof(AtspiDeviceEvent), alignof(AtspiDeviceEvent));
    printf("%s;%zu;%zu\n", "AtspiDeviceEventMask", sizeof(AtspiDeviceEventMask), alignof(AtspiDeviceEventMask));
    printf("%s;%zu;%zu\n", "AtspiDeviceListener", sizeof(AtspiDeviceListener), alignof(AtspiDeviceListener));
    printf("%s;%zu;%zu\n", "AtspiDeviceListenerClass", sizeof(AtspiDeviceListenerClass), alignof(AtspiDeviceListenerClass));
    printf("%s;%zu;%zu\n", "AtspiEvent", sizeof(AtspiEvent), alignof(AtspiEvent));
    printf("%s;%zu;%zu\n", "AtspiEventListener", sizeof(AtspiEventListener), alignof(AtspiEventListener));
    printf("%s;%zu;%zu\n", "AtspiEventListenerClass", sizeof(AtspiEventListenerClass), alignof(AtspiEventListenerClass));
    printf("%s;%zu;%zu\n", "AtspiEventListenerMode", sizeof(AtspiEventListenerMode), alignof(AtspiEventListenerMode));
    printf("%s;%zu;%zu\n", "AtspiEventType", sizeof(AtspiEventType), alignof(AtspiEventType));
    printf("%s;%zu;%zu\n", "AtspiHyperlink", sizeof(AtspiHyperlink), alignof(AtspiHyperlink));
    printf("%s;%zu;%zu\n", "AtspiHyperlinkClass", sizeof(AtspiHyperlinkClass), alignof(AtspiHyperlinkClass));
    printf("%s;%zu;%zu\n", "AtspiKeyDefinition", sizeof(AtspiKeyDefinition), alignof(AtspiKeyDefinition));
    printf("%s;%zu;%zu\n", "AtspiKeyEventMask", sizeof(AtspiKeyEventMask), alignof(AtspiKeyEventMask));
    printf("%s;%zu;%zu\n", "AtspiKeyEventType", sizeof(AtspiKeyEventType), alignof(AtspiKeyEventType));
    printf("%s;%zu;%zu\n", "AtspiKeyListenerSyncType", sizeof(AtspiKeyListenerSyncType), alignof(AtspiKeyListenerSyncType));
    printf("%s;%zu;%zu\n", "AtspiKeyMaskType", sizeof(AtspiKeyMaskType), alignof(AtspiKeyMaskType));
    printf("%s;%zu;%zu\n", "AtspiKeySet", sizeof(AtspiKeySet), alignof(AtspiKeySet));
    printf("%s;%zu;%zu\n", "AtspiKeySynthType", sizeof(AtspiKeySynthType), alignof(AtspiKeySynthType));
    printf("%s;%zu;%zu\n", "AtspiLocaleType", sizeof(AtspiLocaleType), alignof(AtspiLocaleType));
    printf("%s;%zu;%zu\n", "AtspiMatchRule", sizeof(AtspiMatchRule), alignof(AtspiMatchRule));
    printf("%s;%zu;%zu\n", "AtspiMatchRuleClass", sizeof(AtspiMatchRuleClass), alignof(AtspiMatchRuleClass));
    printf("%s;%zu;%zu\n", "AtspiModifierType", sizeof(AtspiModifierType), alignof(AtspiModifierType));
    printf("%s;%zu;%zu\n", "AtspiObject", sizeof(AtspiObject), alignof(AtspiObject));
    printf("%s;%zu;%zu\n", "AtspiObjectClass", sizeof(AtspiObjectClass), alignof(AtspiObjectClass));
    printf("%s;%zu;%zu\n", "AtspiPoint", sizeof(AtspiPoint), alignof(AtspiPoint));
    printf("%s;%zu;%zu\n", "AtspiRange", sizeof(AtspiRange), alignof(AtspiRange));
    printf("%s;%zu;%zu\n", "AtspiRect", sizeof(AtspiRect), alignof(AtspiRect));
    printf("%s;%zu;%zu\n", "AtspiRelation", sizeof(AtspiRelation), alignof(AtspiRelation));
    printf("%s;%zu;%zu\n", "AtspiRelationClass", sizeof(AtspiRelationClass), alignof(AtspiRelationClass));
    printf("%s;%zu;%zu\n", "AtspiRelationType", sizeof(AtspiRelationType), alignof(AtspiRelationType));
    printf("%s;%zu;%zu\n", "AtspiRole", sizeof(AtspiRole), alignof(AtspiRole));
    printf("%s;%zu;%zu\n", "AtspiScrollType", sizeof(AtspiScrollType), alignof(AtspiScrollType));
    printf("%s;%zu;%zu\n", "AtspiStateSet", sizeof(AtspiStateSet), alignof(AtspiStateSet));
    printf("%s;%zu;%zu\n", "AtspiStateSetClass", sizeof(AtspiStateSetClass), alignof(AtspiStateSetClass));
    printf("%s;%zu;%zu\n", "AtspiStateType", sizeof(AtspiStateType), alignof(AtspiStateType));
    printf("%s;%zu;%zu\n", "AtspiTextBoundaryType", sizeof(AtspiTextBoundaryType), alignof(AtspiTextBoundaryType));
    printf("%s;%zu;%zu\n", "AtspiTextClipType", sizeof(AtspiTextClipType), alignof(AtspiTextClipType));
    printf("%s;%zu;%zu\n", "AtspiTextGranularity", sizeof(AtspiTextGranularity), alignof(AtspiTextGranularity));
    printf("%s;%zu;%zu\n", "AtspiTextRange", sizeof(AtspiTextRange), alignof(AtspiTextRange));
    return 0;
}
